### ISSUE TITLE
Angular 15

### ISSUE THREAD

**Issue by kzimny** [jodit/jodit-angular#118]
How to install` jodit-angular` in Angular 15 project? 

![image](https://github.com/jodit/jodit-angular/assets/12007674/d2abb159-fb24-4ec2-a858-195991aec7a1)

**Comment by MrElectroNick** [comment]
Hi @kzimny library versions are still pending for v15 and v16 due to lack of time. As an option you can use 4 files of a library module in your project. You can find it here: https://github.com/jodit/jodit-angular/tree/master/projects/jodit-angular-lib/src/lib
Just put it inside your project and remove dependency to jodit-angular for now but keep jodit itself as dependency

**Comment by kzimny** [comment]
This is great, thank you very much for your quick support!
