### ISSUE TITLE
SSR does not work

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#3]
I have set up the universal app using the standard procedure and I realised when trying to run the application using node I get the following error:

`!function(e,t){ true?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Jodit=t():e.Jodit=t()}("undefined"!=typeof self?self:this,function(){return function(e){function t(n){if(o[n])return o[n].exports;var i=o[n]={i:n,l:!1,exports:{}};return e[n].call(i.exports,i,i.exports,t),i.l=!0,i.exports}var o={};return t.m=e,t.c=o,t.d=function(e,o,n){t.o(e,o)||Object.defineProperty(e,o,{configurable:!1,enumerable:!0,get:n})},t.n=function(e){var o=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(o,"a",o),o},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="/build/",t(t.s=21)}([function(e,t,o){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var n=o(2),i=o(3),r={},s=r.toString,a=r.hasOwnProperty;t.isIE=function(){return-1!=navigator.userAgent.indexOf("MSIE")||/rv:11.0/i.test(navigator.userAgent)};var l=1;t.$$=function(

ReferenceError: window is not defined`

The problem with that is that is happening when I import the JoditAngularModule and unfortunately I can't get this to work. Any ideas about how can it be solved?

**Comment by xdan** [comment]
Sorry but Jodit does not support SSR.

**Comment by CarlosTorrecillas** [comment]
Thanks for letting me know. Are there any plans to make this happen?

**Comment by cbernth** [comment]
I just bumped into the same issue...

Since Angular is by nature SSR enabled and the only meaningful way to do SEO on SPA's is SSR, I think it's quite important to have this support in jodit-angular. 

The other pretty important reason for using (and jodit-angular to support) SSR is that the initial page load time is reduced significantly when receiving a 25kB HTML page over a 1-5MB client app in the first page load. 

There are various approaches to do this, either just check if e.g. 'window' or 'document' is available before starting to use them in code, or mocking the angular component based on browser or server environment.

**Comment by denniskuligin** [comment]
What is the problem to use the native one with allowJs? 
Or, in your webpack config file use declare plug-in and declare window/whatsoeveritrequires

@xdan Кстати, а почему не сделать SSR? ну, оберни им все в isPlatformBrowser 😃

**Comment by helix46** [comment]
This works for me in a production SSR app

`<jodit-editor *ngIf="showJodit" ></jodit-editor>`

  showJodit = false;

  constructor(@Inject(PLATFORM_ID) private platformId: Object) {
    if (isPlatformBrowser(platformId)) {this.showJodit = true;}
  }
